### ISSUE TITLE
[Suggestion] Manifest URLs or equivalent solutions

### ISSUE THREAD

**Issue by rpganalyst** [kid2407/Compendium2Module#1]
In your tutorial there is a point that says:
_"Copy the content of the downloaded zip file into your modules directory"_, but this is only possible for those running the machine that hosts FoundryVTT.
In cases like mine, where I manage modules and compendiums, but the raspberry that hosts Foundry is 1000 km away from me, it would be handy if there was a way to get a manifest url or an equivalent solution.

Thank you very much.

**Comment by kid2407** [comment]
I can certainly see that happening, I could make it so the files get saved on the foundry instance you are on and give out a link that points there. This would only require foundry to be running, not even the specific world.

In theory I could also allow saving the compendium to my server via some service, but that would quickly make me run out of storage space, so what I wrote above would probably the preferable solution :)

**Comment by kid2407** [comment]
I went ahead and set up a project / todo list, and included this feature there.

**Comment by rpganalyst** [comment]
Thank you very much!

**Comment by kid2407** [comment]
And there it is: The ability to generate a manifest URL is available with the [latest release](https://github.com/kid2407/Compendium2Module/releases/tag/1.1.0)!
