### ISSUE TITLE
Any plans to update to support Foundry v10?

### ISSUE THREAD

**Issue by steveculshaw** [kid2407/Compendium2Module#12]
Any plans to update to support Foundry v10?

Cheers,
SteveC.

**Comment by kid2407** [comment]
I'd love to, though I currently do not have the time to do so. If anyone feels like they can make it work in V10, feel free to submit a pull request :)

**Comment by steveculshaw** [comment]
Thanks for the response. 
I wish I could help, but sadly my coding skills are woefully inadequate :-(
JavaScript is black magic to me :-)
Don't even know where to start?

**Comment by kid2407** [comment]
A long while later: I have updated the module to [version 1.2.0](https://github.com/kid2407/Compendium2Module/releases/tag/1.2.0), which makes it compatible with Foundry v10

**Comment by steveculshaw** [comment]
Thank you
