### ISSUE TITLE
Warning messages with v1.1.0 under v10.286

### ISSUE THREAD

**Issue by steveculshaw** [kid2407/Compendium2Module#13]
I'm seeing warning in the console ...

setup.js:145 [compendium2module] The module "compendium2module" is using "author" which is deprecated in favor of "authors"
#logPackageWarnings @ setup.js:145
setup.js:145 [compendium2module] The module "compendium2module" is using the old flat core compatibility fields which are deprecated in favor of the new "compatibility" object

![image](https://user-images.githubusercontent.com/64320/192315487-f4559961-b434-4f95-947b-70c22a0859b4.png)

**Comment by kid2407** [comment]
Should be an easy fix, should probably be done with the update to v10, see #12 for reference.

**Comment by kid2407** [comment]
A long while later: I have updated the module to [version 1.2.0](https://github.com/kid2407/Compendium2Module/releases/tag/1.2.0), which makes it compatible with Foundry v10
