### ISSUE TITLE
Folders are not saving.

### ISSUE THREAD

**Issue by Akallabeth13666** [kid2407/Compendium2Module#14]
Hi,

Not sure if I am doing something wrong or not. 
But when using the exported compendium as a module folder structure is not saved.

More details are in the attachment.

Anyone knows if am I doing something wrong or if it is a bug?
![Issue](https://user-images.githubusercontent.com/95130435/194542063-2f70ad46-7544-4cde-8375-4ce94d9674ee.JPG)

**Comment by kid2407** [comment]
Hi, I never tested this with compendium folders, so it quite likely it is broken / not working as intended.

**Comment by Akallabeth13666** [comment]
Hi,

Yea, I tested that on v9 so that is definitely not v10 issue.
I guess I just want confirmation if anyone else had exactly the same issue when folders are present or if it is something on my side/module conflict or something.

Any plans to perhaps deal with this issue for v10?

**Comment by kid2407** [comment]
If I had the time to dig into it, then yes...

**Comment by Akallabeth13666** [comment]
It was a module conflict I believe.
