### ISSUE TITLE
[Feature] Include Image

### ISSUE THREAD

**Issue by brunocalado** [kid2407/Compendium2Module#2]
Hi. This module is just amazing. It should merged into core.

Can you make it read the images links and copy them to the generated module?

So, you can have this images into the generated module instead the original path.
![image](https://user-images.githubusercontent.com/4999783/154568957-9d5dc017-b53e-4443-bb37-ec55b530c0d4.png)

**Comment by kid2407** [comment]
Yes, that is on the list to include next.
After all if I do it, it should be done properly :)

**Comment by kid2407** [comment]
I went ahead and set up a project / todo list, and included this feature there.

**Comment by kid2407** [comment]
And implemented with the [latest release](https://github.com/kid2407/Compendium2Module/releases/1.0.2)!
