### ISSUE TITLE
[Bug] Image paths containing spaces no longer work when exporting with images

### ISSUE THREAD

**Issue by brunocalado** [kid2407/Compendium2Module#3]
I'm trying to export a compedium with images. But, special characters on the file name of the images generate errors.

Is it possible to add some error handling?

Tks

![image](https://user-images.githubusercontent.com/4999783/154748557-5cbd887f-aae6-4cfd-b5f5-22f8cd75772c.png)

![image](https://user-images.githubusercontent.com/4999783/154748950-be6b2fe8-8c2d-423f-ba03-c7df2d3253e9.png)

**Comment by kid2407** [comment]
Special characters, of course!
Will be fixed of course.

I assume the original file had a space in it where the %20 now is?

**Comment by brunocalado** [comment]
> 
yes

`Fantasia-Heavy Metal.jpg`

**Comment by brunocalado** [comment]
This is the file working on the world.
![image](https://user-images.githubusercontent.com/4999783/154750198-35e43ae1-5b85-46ab-82d8-dc90b245f4f4.png)

**Comment by kid2407** [comment]
Resolved with the [latest release](https://github.com/kid2407/Compendium2Module/releases/tag/1.0.4).
