### ISSUE TITLE
Token image not exported if different from actor image

### ISSUE THREAD

**Issue by apetina** [kid2407/Compendium2Module#4]
If the actor and the token have different images, it seems the module only export actor one, but no token's.
<img width="364" alt="image" src="https://user-images.githubusercontent.com/78870451/154796029-ffd38bb1-658b-4be0-9b24-24bfcf9a1f98.png">

**Comment by kid2407** [comment]
Noted, will change it so the token image also gets updated accordingly.

**Comment by kid2407** [comment]
Version 1.0.3 now supports properly copying the token image.
